services:
  express:
    image: ghcr.io/pamweng/early-intervention:backend-api-${IMAGE_TAG:-dev}
    ports:
      - ${PORT:-3000}:3000
    volumes:
      - ./upload:/app/upload
    env_file:
      - .env
    extra_hosts:
      - "localhost:host-gateway"
    restart: unless-stopped
